<?php
    $fieldname=$_POST['fieldname'];
    $type=$_POST['type'];
    $length=$_POST['length'];
    $decimal=$_POST['decimal'];
    $thai=$_POST['thai'];
    $description=$_POST['description'];
    $sample=$_POST['sample'];
    $remarks=$_POST['remarks'];
    $generatedBy = $_POST['gen'];
    $EDW = $_POST['EDW'];
    $username=$_POST['username'];
    $userdes=$_POST['userdes'];
    $oldFieldName=$_POST['oldFieldName'];
    // $oldFieldId = $_POST['oldFieldId'];
    // echo $fieldname + ' ' + $type;
    
	require_once"connect.php";
    $con=new mysqli(DB_HOST,DB_USER,DB_PASSWORD,DB_name);
   
	if($con){
	    // update array
	    $update=array();
	    // reteive old data
	    $store= array();
	 $sql=$GLOBALS['con']->query("SELECT * from field WHERE field_name='$oldFieldName'");
      while($row = mysqli_fetch_array($sql)){
              array_push($store,$row);
      }
      //print_r($store[0][1]);
      // check updating database
      $count=0;
      if(strcmp($store[0][1],$fieldname)!=0){
          array_push($update,"Field name: ".$store[0][1]." => $fieldname, ");
        //   print_r($update[$count]);
          ++$count;
          //echo("equal");
      }
      if(strcmp($store[0][2],$type)!=0){
          array_push($update,"Type: ".$store[0][2]." => $type, ");
        //   print_r($update[$count]);
          ++$count;
      }
      if(strcmp($store[0][3],$length)!=0){
          array_push($update,"Length: ".$store[0][3]." => $length, ");
        //   print_r($update[$count]);
          ++$count;
      }
      if(strcmp($store[0][4],$decimal)!=0){
           $represent;
            if(strcmp($store[0][4],"")==0){
              $store[0][4]="(null)";
          }if(strcmp($decimal,"")==0){
              $represent="(null)";
          }else{
              $represent=$decimal;
          }
          
          array_push($update,"Decimal point: ".$store[0][4]." => $represent, ");
        //   print_r($update[$count]);
          ++$count;
      }
      if(strcmp($store[0][5],$thai)!=0){
           $represent2;
            if(strcmp($store[0][5],"")==0){
              $store[0][5]="(null)";
          }if(strcmp($thai,"")==0){
              $represent2="(null)";
          }else{
              $represent2=$thai;
          }
          
          array_push($update,"Thai: ".$store[0][5]." => $represent2, ");
        //   print_r($update[$count]);
          ++$count;
      }
       if(strcmp($store[0][6],$description)!=0){
            $represent3;
            if(strcmp($store[0][6],"")==0){
              $store[0][6]="(null)";
          }if(strcmp($description,"")==0){
              $represent3="(null)";
          }else{
              $represent3=$description;
          }
          array_push($update,"Description: ".$store[0][6]." => $represent3, ");
        //   print_r($update[$count]);
          ++$count;
      }
       if(strcmp($store[0][7],$sample)!=0){
            $represent4;
            if(strcmp($store[0][7],"")==0){
              $store[0][7]="(null)";
          }if(strcmp($sample,"")==0){
              $represent4="(null)";
          }else{
              $represent4=$sample;
          }
          array_push($update,"Sample data: ".$store[0][7]." => $represent4, ");
        //   print_r($update[$count]);
          ++$count;
      }
       if(strcmp($store[0][8],$remarks)!=0){
            $represent5;
            if(strcmp($store[0][8],"")==0){
              $store[0][8]="(null)";
          }if(strcmp($remarks,"")==0){
              $represent5="(null)";
          }else{
              $represent5=$remarks;
          }
          array_push($update,"Remarks: ".$store[0][8]." => $represent5, ");
        //   print_r($update[$count]);
          ++$count;
      }
       if(strcmp($store[0][9],$generatedBy)!=0){
          array_push($update,"Generated by: ".$store[0][9]." => $generatedBy, ");
        //   print_r($update[$count]);
          ++$count;
      }
       if(strcmp($store[0][10],$EDW)!=0){
          array_push($update,"Sent to EDW:   ".$store[0][10]." => $EDW");
        //   print_r($update[$count]);
      }
    //combine updated
    $CombineUpdate="";
    $saveUpdated=0;
    while($count>=0){
        $CombineUpdate.=$update[$saveUpdated];
        $saveUpdated++;
        $count--;
    }
    // echo(".....".$CombineUpdate);

	$sql3=$con->prepare("select distinct idHistory from History;");
	$sql3->execute();
	$sql3->store_result();
	$idHistory =(int)$sql3->num_rows;
	$sqlUpdate= 'UPDATE field SET field_name="'.$fieldname.'", type="'.$type.'", length="'.$length.'", decimal_point="'.$decimal.'", thai_char="'.$thai.'", description="'.$description.'", sample_data="'.$sample.'", remarks="'.$remarks.'", generated_by="'.$generatedBy.'", send_to_edw="'.$EDW.'" where field_name="'.$oldFieldName.'";';
	
	$sql2="INSERT INTO History(idHistory,name,timestamp,description,request,query,updated) values('$idHistory','$username',CURRENT_TIMESTAMP(),'$userdes','Edit Field','$sqlUpdate','$CombineUpdate')";
	
	 if(mysqli_query($con, $sqlUpdate)&&mysqli_query($con, $sql2)){
		 echo "<script>
		 alert('Field edited successfully.');
		 window.location.href='FieldDic.php';
		 </script>";
	 }else{
	     echo "<script>
		 alert('Failed to edit field. Please try again.');
		 window.location.href='FieldDic.php';
		 </script>";
	 }  
	} 
	else{
		echo "<script>
		 alert('Cann't connect to server. Please try again.');
		 window.location.href='FieldDic.php';
		 </script>";
	}
	
    mysqli_close($con);
    
	
?>