<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="mystyle.css">
    <link href="https://fonts.googleapis.com/css?family=Athiti|Hind" rel="stylesheet">
    <title>Audit Log - Import</title>
</head>
<body>
    <table class="error-table">
        <tbody>
            <tr>
                <th>Event Code</th>
                <th>Sub Event Code</th>
                <th>Field</th>
                <th>Mandatory</th>
                <th>Value</th>
                <th>Generated By</th>
                <th>Send to EDW</th>
                <th>Status</th>
            </tr>
            <?php
require_once 'excel/PHPExcel.php';
include 'excel/PHPExcel/IOFactory.php';
require_once"connect.php";
$con=new mysqli(DB_HOST,DB_USER,DB_PASSWORD,DB_name);
$username=$_POST['username'];
$userdes=$_POST['userdes'];

// funtion 
function ExistingCheck($code,$sub,$field,$man,$value,$gen,$edw,$versionID,$username,$userdes){
    // check event in event table
   $queryEvent=$GLOBALS['con']->query("SELECT * from event WHERE event_code='$code' and sub_event_code='$sub'");
   $event = array(array());
   while($row = mysqli_fetch_array($queryEvent)){
       array_push($event,$row);
   }
//   echo 'event = '.count($event).' ';
   if(count($event) > 1){
       // check field in field table
       $queryField = $GLOBALS['con']->query("SELECT * from field WHERE field_name='$field'");
       $fieldTable = array(array());
       while($row = mysqli_fetch_array($queryField)){
           array_push($fieldTable,$row);
       }
    //   echo 'field = '.count($fieldTable).' ';
        if(count($fieldTable) > 1){
            // check event, field in relation table
                $queryRelation = $GLOBALS['con']->query('select * from event_field_relation where event_code = '.$code.' and sub_event_code = "'.$sub.'" and field_name = "'.$field.'";');
                $update=array(); // array keep changing data
                $store = array(); //array keep old relation
                   while($row = mysqli_fetch_array($queryRelation)){
                       array_push($store,$row);
                   }
            //   echo 'relation = '.count($relation).' ';
                if(count($store) > 0){
                    // retrive old relation information
                    // check updating database
                  $count=0;
                  if(strcmp($store[0][0],$code)!=0){
                      array_push($update,"Event code: ".$store[0][0]." => $code, ");
                    //   print_r($update[$count]);
                      ++$count;
                      //echo("equal");
                  }
                  if(strcmp($store[0][1],$sub)!=0){
                      array_push($update,"Sub event code: ".$store[0][1]." => $sub, ");
                    //   print_r($update[$count]);
                      ++$count;
                  }
                  if(strcmp($store[0][2],$fieldTable[1]["field_id"])!=0){
                      array_push($update,"Field id: ".$store[0][2]." => ".$fieldTable[1]["field_id"].", ");
                    //   print_r($update[$count]);
                      ++$count;
                  }
                  if(strcmp($store[0][3],$field)!=0){
                      array_push($update,"Field : ".$store[0][3]." => $field, ");
                    //   print_r($update[$count]);
                      ++$count;
                  }
                  if(strcmp($store[0][4],$man)!=0){
                      array_push($update,"Mandatory: ".$store[0][4]." => $man, ");
                    //   print_r($update[$count]);
                      ++$count;
                  }
                   if(strcmp($store[0][5],$value)!=0){
                      array_push($update,"Generated value: ".$store[0][5]." => $value, ");
                    //   print_r($update[$count]);
                      ++$count;
                  }
                   if(strcmp($store[0][6],$gen)!=0){
                      array_push($update,"Generated by: ".$store[0][6]." => $gen, ");
                    //   print_r($update[$count]);
                      ++$count;
                  }
                   if(strcmp($store[0][7],$edw)!=0){
                      array_push($update,"Send to EDW: ".$store[0][7]." => $edw, ");
                    //   print_r($update[$count]);
                  }
            
                //combine updated
                $CombineUpdate="";
                $saveUpdated=0;
                while($count>=0){
                    $CombineUpdate.=$update[$saveUpdated];
                    $saveUpdated++;
                    $count--;
                }
            //update old relation information
                
            $sqlUpdate='UPDATE event_field_relation SET event_code = '.$code.', sub_event_code = "'.$sub.'",field_id='.$fieldTable[1]["field_id"].',field_name="'.$field.'",mandatory="'.$man.'",generator_value="'.$value.'",generated_by="'.$gen.'",send_to_edw="'.$edw.'" WHERE event_code = '.$code.' AND sub_event_code = "'.$sub.'" AND field_name = "'.$field.'";';
            
            $sql2="INSERT INTO History(idHistory,name,timestamp,description,request,query,updated) values('$versionID','$username',CURRENT_TIMESTAMP(),'$userdes','Import excel','$sqlUpdate','$CombineUpdate')";
            
            mysqli_query($GLOBALS['con'], $sqlUpdate);
            mysqli_query($GLOBALS['con'], $sql2);
                //$sql->close();
                return true;
        }else{
            // insert new relation
            $sql='INSERT INTO event_field_relation(event_code,sub_event_code,field_id,field_name,mandatory,generator_value,generated_by,send_to_edw) VALUES('.$code.',"'.$sub.'",'.$fieldTable[1]["field_id"].',"'.$field.'","'.$man.'","'.$value.'","'.$gen.'","'.$edw.'");';
            mysqli_query($GLOBALS['con'], $sql);
                
            $updatedString = "Add field( ".$field." )for event ".$code."/".$sub;
                
            $sql2="INSERT INTO History(idHistory,name,timestamp,description,request,query,updated) values('$versionID','$username',CURRENT_TIMESTAMP(),'$userdes','Import excel','$sql','$updatedString')";
                mysqli_query($GLOBALS['con'], $sql2);
                return true;
            }
            
      }else{
          return false;
      }
    }else{
        return false;
    }
}  //end function

if(isset($_POST['upload'])){
$inputFileName =$_FILES['file']['tmp_name']; 
$inputFileType = PHPExcel_IOFactory::identify($inputFileName);  
$objReader = PHPExcel_IOFactory::createReader($inputFileType);  
$objReader->setReadDataOnly(true);  
$objPHPExcel = $objReader->load($inputFileName);  

$objWorksheet = $objPHPExcel->setActiveSheetIndex(0);
$highestRow = $objWorksheet->getHighestRow();
$highestColumn = $objWorksheet->getHighestColumn();

$headingsArray = $objWorksheet->rangeToArray('A1:'.$highestColumn.'1',null, true, true, true);
$headingsArray = $headingsArray[1];

$r = -1;
$namedDataArray = array();
for ($row = 2; $row <= $highestRow; ++$row) {
    $dataRow = $objWorksheet->rangeToArray('A'.$row.':'.$highestColumn.$row,null, true, true, true);
    if ((isset($dataRow[$row]['A'])) && ($dataRow[$row]['A'] > '')) {
        ++$r;
        foreach($headingsArray as $columnKey => $columnHeading) {
            $namedDataArray[$r][$columnHeading] = $dataRow[$row][$columnKey];
        }
    }
}
    $idHistory=$GLOBALS['con']->prepare('SELECT DISTINCT idHistory FROM History;');
    $idHistory->execute();
    $idHistory->store_result();
    $version = $idHistory->num_rows;
    $i = 0;
    if(count($namedDataArray) == 0){
        // echo "<script>
        // alert(\"Please insert your data in excel sheet first.\");
        // window.location.href='import.php';
        // </script>";
        echo '<div style="color: red; text-align: center;">Please insert your data in excel sheet first.</div>';
        echo '<div style="text-align: center; margin-top: 20px;"><button id="confirm-button" onclick=window.location.href="import.php">Back to Import</button></div>';
    }else{
    foreach ($namedDataArray as $result) {
    		$i++;
    		$eventCode = strtoupper(trim($result["EVENT_CODE"]," "));
    		$subEventCode = strtoupper(trim($result["SUB_EVENT_CODE"]," "));
    		$fieldName = strtoupper(trim($result["FIELD"]," "));
    		$mandatory = strtoupper(trim($result["MANDATORY"]," "));
    		$value = strtoupper(trim($result["VALUE"]," "));
    		$generatedBy = strtoupper(trim($result["GENERATED_BY"]," "));
    		$sendToEDW = strtoupper(trim($result["SEND_TO_EDW"]," "));
    		$status = true;
    	
            echo "<tr>";
            // check whether there is any incorrect data pattern in a row( true,false)
            if(preg_match("/^[0-9]+$/", $eventCode)) {
                echo "<td>".$eventCode."</td>";
            }else{
                // echo "Event Code at row ".($i)." has wrong format.</br>";
                echo '<td style="background-color: #ff745b">'.$eventCode.'</td>';
                $status = false;
            }
            if(preg_match("/^[A-Z^0-9]+$/", $subEventCode)) {
                echo "<td>".$subEventCode."</td>";
            }else{
                // echo "Sub Event Code at row ".($i)." has wrong format.</br>";
                echo '<td style="background-color: #ff745b">'.$subEventCode.'</td>';
                $status = false;
            }
            if(preg_match("/^[A-Za-z_]+$/", $fieldName)) {
                echo "<td>".$fieldName."</td>";
            }else{
                echo '<td style="background-color: #ff745b">'.$fieldName.'</td>';
                $status = false;
            }
            if(preg_match("/^[M,O]$/", $mandatory)) {
                echo "<td>".$mandatory."</td>";
            }else{
                echo '<td style="background-color: #ff745b">'.$mandatory.'</td>';
                $status = false;
            }
            if(preg_match("/^[M,O]$/", $value)) {
                echo "<td>".$value."</td>";
            }else{
                if(preg_match("/^[<]$/", substr($value,0,1)) && preg_match("/^[>]$/", substr($value,-1)) && preg_match("/^[.A-Z0-9]+$/", substr($value,1,-1))){
                    echo "<td>&lt;".substr($value,1,-1)."&gt;</td>";
                }else{
                    echo '<td style="background-color: #ff745b;">'.$value.'</td>';
                    $status = false;
                }
            }
            if(preg_match("/^[S,U,F]$/", $generatedBy)) {
                echo "<td>".$generatedBy."</td>";
            }else{
                echo '<td style="background-color: #ff745b">'.$generatedBy.'</td>';
                $status = false;
            }
            if(preg_match("/^[Y,N]$/", $sendToEDW)) {
                echo "<td>".$sendToEDW."</td>";
            }else{
                echo '<td style="background-color: #ff745b">'.$sendToEDW.'</td>';
                $status = false;
            } // check incorrect data in a row
            // if true(all data pattern in a row are correct)
            if($status){
                // check event, field whether existed
                if(ExistingCheck($result["EVENT_CODE"],$result["SUB_EVENT_CODE"],$result["FIELD"],$result["MANDATORY"],$result["VALUE"],$result["GENERATED_BY"],$result["SEND_TO_EDW"],$version,$username,$userdes)){
        		    echo '<td style="background-color: #91ff5b">Success</td>';
        		}else{
        		    echo '<td style="background-color: #ff745b">Fail</td>';
        		  //  break;
        		}
            }else{
                echo '<td style="background-color: #ff745b">Fail</td>';
            }
    }
    /*
    if($wholeStatus){
        $username=$_POST['username'];
        $userdes=$_POST['userdes'];
        $sql="INSERT INTO History(name,timestemp,description) values('$username',CURRENT_TIMESTAMP(),'$userdes')";
        if(mysqli_query($con, $sql)){
            echo '<div style="text-align: center; margin-top: 20px;"><button id="confirm-button" onclick=window.location.href="import.php">Back to Import</button></div>';   
        }else{
            echo '<div style="text-align: center; margin-top: 20px;"><button id="confirm-button" onclick=window.location.href="import.php">Back to Import</button></div>';
        }
    }else{
        echo '<div style="text-align: center; margin-top: 20px;"><button id="confirm-button" onclick=window.location.href="import.php">Back</button></div>';
    } */
    }
    }else{
        echo "<script>
		 alert('No excel file.Please upload excel file!!!');
         window.location.href='import.php';
		 </script>";
    }

    echo '<div style="text-align: center; margin-top: 20px;"><button id="confirm-button" onclick=window.location.href="import.php">Back to Import</button></div>';
    mysqli_close($con);
?>
        </tbody>
    </table>
</body>
</html>