<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="mystyle.css">
    <link rel="shortcut icon" href="./images/LogoS.ico">
    <link href="https://fonts.googleapis.com/css?family=Athiti|Hind" rel="stylesheet">
    <title>Audit Log - Event Details</title>
</head>

<body>
    <div class="web-container">
       <a id="logo-monster" href="EventSum.php"><img src="images/logo-monster-read.png" alt="Audit Monster" height="40"></a>
        <div class="content-container">
            <div class="sidebar">
                <ul>
                    <li onclick="location.href='EventSum.php';">Event Summary</li>
                    <li onclick="location.href='FieldDic.php';">Field Dictionary</li>
                     <li onclick="location.href='export.php';">Export</li>
                    <li onclick="location.href='version-control.php';">Version Control</li>
                    <li onclick="location.href='TutorialPage.php';">Tutorial</li>
                </ul>
            </div>
            <div class="content">
                <?php
                    $eventCode = $_POST['eventCode'];
                    $subEventCode = $_POST['subEventCode']; 
                      $User="U";
                    $System="S";
                    $generated_value="888";
                    require_once"connect.php";
                    $con=new mysqli(DB_HOST,DB_USER,DB_PASSWORD,DB_name);
                 	$mysql_qry = 'select * from event_field_relation where event_code = '.$eventCode.' and sub_event_code = "'.$subEventCode.'";';
                    $result = mysqli_query($con ,$mysql_qry);
                    if($subEventCode == 0){
                        $mysql_qry2 = 'select * from event where event_code = '.$eventCode.' and sub_event_code = '.$subEventCode.';';
                    }else{
                        $mysql_qry2 = 'select * from event where event_code = '.$eventCode.' and sub_event_code = "'.$subEventCode.'";';
                    }
                    $result2 = mysqli_query($con ,$mysql_qry2);
                    $event = array();
                    while($row = mysqli_fetch_array($result2)) {
                         array_push($event,$row);
                    }
                    echo '<div class=page-header-area>';
                    echo '<h2 style="display: inline-block;">Event Details</h2>';
                    echo '</div>';
                    echo '<div>Event Code : '.$event[0]["event_code"].'</div>';
                    echo '<div>Sub Event Code : '.$event[0]["sub_event_code"].'</div>';
                    echo '<div>Event Name(EN) : '.$event[0]["event_name_en"].'</div>';
                    echo '<div>Event Name(TH) : '.$event[0]["event_name_th"].'</div>';
                    echo '<div>Send to PRM : '.$event[0]["send_to_prm"].'</div>';
                    echo '<div>Send to GL : '.$event[0]["send_to_gl"].'</div>';
                    echo '<div>Send to EDW : '.$event[0]["send_to_edw"].'</div>';
                    echo '<div>Description : '.$event[0]["description"].'</div>';
                    echo '<div>Endpoints : '.$event[0]["endpoints"].'</div>';
                    
                    ?>
                    <div id="div1">
                         <table class="edit-page-table">
                             <tbody>
                                 <tr>
                                     <th width="5%">ID</th>
                                     <th width="20%">Field</th>
                                     <th width="10%">Value</th>
                                     <th width="10%">Generated By</th>
                                     <th width="1%"></th>
                                </tr>
                            </tbody>    
                            </table>
                    </div>
                    <div id="div2">
                        <table class="edit-page-table">
                            <tbody>
                    <?php
                    while($row = mysqli_fetch_array($result)) {
                         if(strcmp($row['generated_by'],$User)==0){
                        		    $generated_value="User";
                        		}else if(strcmp($row['generated_by'],$System)==0){
                        		    $generated_value="System";
                        		}else{
                        		    $generated_value="Other fields";
                        		}
                        if($row['field_name'] == "INFORMATION_1"){
                            echo'<tr>
                                <td>'.$row['field_id'].'</td>
                             	<td>'.$row['field_name'].'</td>
                             	<td>&lt;'.substr($row['generator_value'],1,-1).'&gt; ('.$row['mandatory'].')</td>
                                <td>'.$generated_value.'</td>
                            </tr>';
                        } else if($row['field_name'] == "INFORMATION_2"){
                            echo'<tr>
                                <td>'.$row['field_id'].'</td>
                             	<td>'.$row['field_name'].'</td>
                             	<td>&lt;'.substr($row['generator_value'],1,-1).'&gt; ('.$row['mandatory'].')</td>
                             	<td>'.$generated_value.'</td>
                            </tr>';
                        } else if($row['field_name'] == "INFORMATION_3"){
                            echo'<tr>
                                <td>'.$row['field_id'].'</td>
                             	<td>'.$row['field_name'].'</td>
                             	<td>&lt;'.substr($row['generator_value'],1,-1).'&gt; ('.$row['mandatory'].')</td>
                             	<td>'.$generated_value.'</td>
                            </tr>';
                        } else if($row['field_name'] == "INFORMATION_4"){
                            echo'<tr>
                                <td>'.$row['field_id'].'</td>
                             	<td>'.$row['field_name'].'</td>
                             	<td>&lt;'.substr($row['generator_value'],1,-1).'&gt; ('.$row['mandatory'].')</td>
                             	<td>'.$generated_value.'</td>
                            </tr>';
                        } else if($row['field_name'] == "INFORMATION_5"){
                            echo'<tr>
                                <td>'.$row['field_id'].'</td>
                             	<td>'.$row['field_name'].'</td>
                             	<td>&lt;'.substr($row['generator_value'],1,-1).'&gt; ('.$row['mandatory'].')</td>
                             	<td>'.$generated_value.'</td>
                            </tr>';
                        } else if($row['field_name'] == "INFORMATION_6"){
                            echo'<tr>
                                <td>'.$row['field_id'].'</td>
                             	<td>'.$row['field_name'].'</td>
                             	<td>&lt;'.substr($row['generator_value'],1,-1).'&gt; ('.$row['mandatory'].')</td>
                             	<td>'.$generated_value.'</td>
                            </tr>';
                        } else {
                            echo'<tr>
                                <td width="5%">'.$row['field_id'].'</td>
                             	<td width="20%">'.$row['field_name'].'</td>
                             	<td width="10%">'.$row['generator_value'].'</td>
                             	<td width="10.2%">'.$generated_value.'</td>
                            </tr>';
                        }
                    }
                    echo '</tbody></table>'
                ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</body>
</html>